server:
  port: 11000
  compression:
    enabled: true
    
spring:
  profiles.active: development
  output.ansi.enabled: ALWAYS

---
spring:
  profiles: development
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job_marketplace?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc.time_zone: UTC
        ddl-auto: update
        show-sql: true
        format-sql: true
        type: trace
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
---
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  
  